name: Build and Push
on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read

env:
  IMAGE_REPO: gatus-ecs-deployment

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Debug OIDC token claims
        run: |
          curl -sH "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" \
            | jq -r '.value' | cut -d. -f2 | base64 -d 2>/dev/null | jq .
      - name: checkout code
        uses: actions/checkout@v4

      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-2

      - name: login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: build image
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/${{ env.IMAGE_REPO }}:${{ github.sha }} .

      - name: push image
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.IMAGE_REPO }}:${{ github.sha }}


  