name: Terraform Destroy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  IMAGE_REPO: gatus-ecs-deployment

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-2

      - name: login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.16.4

      - name: terraform init
        run: terraform init

      - name: terraform destroy
        run: |
          terraform destroy -auto-approve \
            -var="gatus_image=${{ steps.login-ecr.outputs.registry }}/${{ env.IMAGE_REPO }}:${{ github.sha }}" \
            -var="aws_region=eu-west-2"